global:
  scrape_interval:     5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
  - 'my_alert_rules1.alert'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'citizen-service'
    static_configs:
    - targets: ['host.docker.internal:9444']
    tls_config:
      insecure_skip_verify: true
    scheme: https
    basic_auth:
      username: admin
      password: admin
networks:
  - monitoring
