server:
  port: 7201

  boot:
    admin:
      client:
        url: http://localhost:7208

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:7200/eureka/

spcloud:
  cassandra:
    contact:
      point: localhost
    port : 9042
    keyspace:
      name: springcloud

    username : cassandra
    password : cassandra