server:
  port: 7200

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411/

  boot:
    admin:
      client:
        url: http://localhost:7208

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7200/eureka/